version: '3.8'

services:

  # db:
  #   image: postgres:12
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_DB=pulsar
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - ./volumes/postgres/data:/var/lib/postgresql/data/

  web:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
    image: fastapi-web
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log_level=info --reload

  worker:
    image: fastapi-web
    command: celery -A core.celery worker  --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
