version: "3.7"

services:

  django:
    build: django
    ports:
      - 8000:8000
    volumes:
      - ./django:/app
  
  djangodb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: djangodb
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: django
    ports:
      - 33061:3306
    volumes:
      - db-data-django:/var/lib/mysql

  fastapi:
    build: fastapi
    ports:
      - 3000:3000
    volumes:
      - ./fastapi:/app

  fastapidb:
    container_name: fastapidb
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapidb
    volumes:
      - db-data-fastapi:/var/lib/postgresql/data/
    ports:
      - 54321:5432


volumes:
  db-data-fastapi:
  db-data-django: