version: "3.8"

services:
  db:
    ports:
      - 5432:5432
  app:
    command: bash -c "aerich upgrade && python manage.py serve --host 0.0.0.0 --port 8000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    ports: 
      - 80:80
  flower:
    ports:
      - 5556:5555



