version: "3.8"

services:

  db:
    container_name: pgsql
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file: 
      - ./.env
  app:
    container_name: app
    <<: &app
      build: .
      volumes:
        - ./:/usr/src/app
      restart: always
      depends_on:
        - db
  redis:
    container_name: redis
    image: redis:6.2-alpine
  celery:
    container_name: celery
    <<: *app
    command: celery -A core.celery worker --loglevel=info
    depends_on:
      - redis
  flower:
    container_name: flower
    <<: *app
    command: celery -A core.celery flower --port=5555
    depends_on:
      - redis

volumes: 
   db-data: