version: "3.8"

services:
  db:
    ports:
      - 5432:5432
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - app
    ports: 
      - 80:80
  flower:
    ports:
      - 5556:5555



