version: "3.8"

services:
  db:
    ports:
      - 5432:5432
  app:
    command: bash -c "aerich upgrade && python manage.py serve"
    ports:
      - 8000:8000
  flower:
    ports:
      - 5555:5555

