version: "3.7"

services:

 
  db:
    container_name: fastapidb
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapidb
    volumes:
      - db-data-fastapi:/var/lib/postgresql/data/
    ports:
      - 54321:5432


  app:
    <<: &app
      build: .
      volumes:
        - ./:/app
      restart: always
      depends_on:
        - db
    command: uvicorn main:app --reload --host=0.0.0.0 --port=3000
    ports:
      - 3000:3000

  queue:
    <<: *app
    command: python -u consumer.py

volumes:
  db-data-fastapi: